export const LOAD_TRAINERS_SUCCESS = 'LOAD_TRAINERS_SUCCESS';
export const UPDATE_TRAINER_SUCCESS = 'UPDATE_TRAINER_SUCCESS';
export const CREATE_TRAINER_SUCCESS = 'CREATE_TRAINER_SUCCESS';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';